sonar.projectKey=hanixd1_PcSystemStore
sonar.organization=hanixd1

sonar.sources=backend/src,frontend,ai-service
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/coverage/**,docs/**

sonar.python.version=3.11